name: ComputerStore
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: "16.0"
targets:
  ComputerStore:
    type: application
    platform: iOS
    sources: ComputerStore
    settings:
      base:
        SWIFT_VERSION: 5.9
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.computerstore
        INFOPLIST_FILE: ComputerStore/Info.plist
